services:
  backend:
    build: ./backend
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT}
    depends_on:
      - mongodb
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data: