services:
  backend:
    build: ./back-end
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT}
    depends_on:
      - mongodb
    volumes:
      - ./back-end:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  frontend:
    build:
      context: ./front-end
      args:
        VITE_GOOGLE_API_KEY: ${VITE_GOOGLE_API_KEY}
        VITE_GOOGLE_SHEETS_ID: ${VITE_GOOGLE_SHEETS_ID}
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data: