services:
  backend:
    build: ./backend
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_SHEETS_ID=${GOOGLE_SHEETS_ID}
      - GIANTBOMB_API_KEY=${GIANTBOMB_API_KEY}
      - RAWG_API_KEY=${RAWG_API_KEY}
      - EMAILJS_SERVICE_ID=${EMAILJS_SERVICE_ID}
      - EMAILJS_TEMPLATE_ID=${EMAILJS_TEMPLATE_ID}
      - EMAILJS_PUBLIC_KEY=${EMAILJS_PUBLIC_KEY}
      - EMAILJS_PRIVATE_KEY=${EMAILJS_PRIVATE_KEY}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    profiles: ["dev"]

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data: